- name: Deploy mqtt-blink1
  hosts: all
  become: true
  gather_facts: true
  roles:
    - role: uhlig-it.simple_systemd_service
      vars:
        program:
          name: mqtt-blink1
          runtime_user: mqtt-blink1
          binary: https://github.com/uhlig-it/mqtt-blink1/releases/download/v1.0.1/mqtt-blink1-linux-armv7.tar.gz
          description: Controls a Blink1 via MQTT
          environment:
            MQTT_URL: "{{ mqtt_url }}"
      become: true
